// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHtUMHUo_hKLHe6lNW7SIH9oSxMn__G4',
    appId: '1:287844451372:web:9b0c88b41493b0ad4fbd89',
    messagingSenderId: '287844451372',
    projectId: 'solanity-d0829',
    authDomain: 'solanity-d0829.firebaseapp.com',
    storageBucket: 'solanity-d0829.firebasestorage.app',
    measurementId: 'G-YDCXL5NLB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2bw9lvtMwiN4Z1RYnqPngQ8pa8S0nmcM',
    appId: '1:287844451372:android:a0c3cafcbcae3dc94fbd89',
    messagingSenderId: '287844451372',
    projectId: 'solanity-d0829',
    storageBucket: 'solanity-d0829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLFKZjzRDro1rIz5tX2NpLoq3SPNll8o',
    appId: '1:287844451372:ios:f87d25364d8e81054fbd89',
    messagingSenderId: '287844451372',
    projectId: 'solanity-d0829',
    storageBucket: 'solanity-d0829.firebasestorage.app',
    iosBundleId: 'com.example.solanityFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGLFKZjzRDro1rIz5tX2NpLoq3SPNll8o',
    appId: '1:287844451372:ios:f87d25364d8e81054fbd89',
    messagingSenderId: '287844451372',
    projectId: 'solanity-d0829',
    storageBucket: 'solanity-d0829.firebasestorage.app',
    iosBundleId: 'com.example.solanityFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSHtUMHUo_hKLHe6lNW7SIH9oSxMn__G4',
    appId: '1:287844451372:web:79af2e2e9dfc68194fbd89',
    messagingSenderId: '287844451372',
    projectId: 'solanity-d0829',
    authDomain: 'solanity-d0829.firebaseapp.com',
    storageBucket: 'solanity-d0829.firebasestorage.app',
    measurementId: 'G-TQ9799KKPG',
  );
}
